name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
        include:
          - python-version: '3.8'
            os: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox poetry
      - name: Run tests
        env:
          TOXENV: py${{ matrix.python-version }}
        run: tox -e $TOXENV

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox codecov poetry
      - name: Run tests with coverage
        env:
          TOXENV: py${{ matrix.python-version }}
        run: tox -e $TOXENV -- --cov=. --cov-report=xml
      - name: Upload coverage to Codecov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: codecov
